version: '3'
services:
  ros_noetic:
    build: .
    volumes:
      - .:/catkin_ws
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority:rw
      - /dev:/dev
    environment:
      - DISPLAY=unix$DISPLAY
      - QT_X11_NO_MITSHM=1
      - LIBGL_ALWAYS_SOFTWARE=1
      - MESA_GL_VERSION_OVERRIDE=3.3
      - XDG_RUNTIME_DIR=/tmp/runtime-root
    network_mode: host
    privileged: true 